- hosts: all
  become: true
  tasks:
  - name: Update APT package repos cache
    become: true
    apt:
      update_cache: yes

  - name: Install Java OpenJDK
    become: yes
    apt:
      name: "{{ package }}"
      state: present
    vars:
     package:
       - openjdk-11-jdk

  - name: Add jenkins apt repo key
    apt_key: url=https://pkg.jenkins.io/debian-stable/jenkins.io.key state=present
  - name: Configure the Jenkins repo
    apt_repository: repo='deb https://pkg.jenkins.io/debian-stable binary/' state=present
  - name: Install Jenkins
    apt: name=jenkins update_cache=yes
  - name: Ensure Jenkins is up and running
    service: name=jenkins state=started
  
  
  - name: Check for Python
    raw: test -e /usr/bin/python
    changed_when: false
    failed_when: false
    register: check_python

  - name: Install Python
    raw: apt -y update && apt install -y python-is-python3
    when: check_python.rc != 0
     
